name: Download and Upload File

on:
  push:
    branches: [ main ]  # 触发工作流的条件，例如在推送到 main 分支时

jobs:
  download_and_upload:
    runs-on: ubuntu-latest  # 选择运行环境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download file
        run: |
          curl -v https://redirector.gvt1.com/edgedl/android/studio/install/2024.1.1.11/android-studio-2024.1.1.11-windows.exe
          curl -o android-studio-2024.1.1.11-windows.exe -L https://redirector.gvt1.com/edgedl/android/studio/install/2024.1.1.11/android-studio-2024.1.1.11-windows.exe  # 使用 curl 命令下载文件
          
      - name: Upload to repository
        run: |
          git config --global user.email "flywaver@qq.com"
          git config --global user.name "flywaver"
          git add android-studio-2024.1.1.11-windows.exe
          git commit -m "android-studio-2024.1.1.11-windows.exe"
          git push
